services:
  java-apps:
    build: .
    volumes:
      - ./data:/app/data
      - ./backup:/app/backup

  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "80:80"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes